---
title: "Wzory"
author: "Krzysztof Pleskot"
date: "2024-02-26"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


## Równanie dwumianowe

\[
P(r; n, p) = \binom{n}{r}p^r(1-p)^{n-r}
\]

\(P(r; n, p)\) - Prawdopodobieństwo wystąpienia \(r\) razy jakiegos zjawiska przy \(n\) probach, w momencie kiedy ogolne prawdopodobienstwo wystapienia tego zjawiska wynosi \(p\)

\(\binom{n}{r}\) - współczynnik dwumianowy zdefiniowany jako:

\[
\binom{n}{r} = \frac{n!}{r!(n-r)!}
\]
gdzie, \(n\) oznacza liczbę prób, a \(r\) liczbę wystąpienia sukcesu

## Silnia

\[
n! = 1 \cdot 2 \cdot 3 \cdot \ldots \cdot (n-1) \cdot n
\]

## Kolejne kroki dochodzenia do wzoru dla równania dwumianowego

Prawdopodobieństwo sukcesu wynosi \(p\). Jest znane albo je zakładamy

## Kolejne kroki dochodzenia do wzoru dla równania dwumianowego

Prawdopodobieństow porażki równe jest dlatego \(1-p\)

## Kolejne kroki dochodzenia do wzoru dla równania dwumianowego

Prawdopodobieństwo, że \(n\) kolejnych prób będzie porażką wynosi \(P = (1 - p)^n\)

## Kolejne kroki dochodzenia do wzoru dla równania dwumianowego

Prawdopodobieństwo, że \(n\)ta próba będzie sukcesem, a wszystkie wczesniejsze porażką wynosi \(P = (1-p)^{n-1}p\)

## Kolejne kroki dochodzenia do wzoru dla równania dwumianowego

Jeśli sukces ma być jeden, ale nie ma znaczenia przy którym zdarzeniu wystąpi, to prawdopodobieństwo musi uwzględnić liczebność próby, dlatego  \(P = n(1-p)^{n-1}p\)

## Kolejne kroki dochodzenia do wzoru dla równania dwumianowego

Z poprzednich rownan mozemy wywnioskować, że \(P=(1-p)^{n-r}p^r\)

## Kolejne kroki dochodzenia do wzoru dla równania dwumianowego

Jeśli wezmiemy poprzednie rownanie i przyjmiemy, że porażki i zwycięstwa mogą występować w dowolnej konfiguracji, to równanie \(P=(1-p)^{n-r}p^r\) będziemy musieli przemnożyć przez współczynnik dwumianowy \(\binom{n}{r}\), bo określa on liczbę wszystkich możliwych kombinacji w których będziemy mieli \(r\) sukcesów przy \(n\) próbach 

W efekcie otrzymujemy docelowe równanie:

\[
P(r; n, p) = \binom{n}{r}p^r(1-p)^{n-r}
\]

## Percentyl

\[
\text{percentile of } x_i=100(\frac{\text{rank of } x_i}{n})
\]

Istnieje wiele różnych podejść do obliczania percentyli w sytuacji, w której rangi się powtarzają

## Symbole we wzorach

Dla populacji najczęściej litery greckie, a dla próby litery rzymskie

## Średnia arytmetyczna

\[
\bar{X} = \frac{\sum_{i=1}^{n} x_i}{n}
\]

## Odchylenie standardowe i wariancja

- Odchylenie standardowe: \(\sigma = \sqrt{\frac{\sum_{i=1}^{n}(x_i - \mu)^2}{n}}\)

- Wariancja: \(\sigma^2 = \frac{\sum_{i=1}^{n}(x_i - \mu)^2}{n}\)

(wzory dla próby statystycznej zamiast \(n\) mają \(n-1\))

Po co kwadrat we wzorach?

- suma kwadratów: \(SS = \sum_{i=1}^{n}(x_i - \mu)^2\) 

## Skośność i kurtoza

Skośność: \[ \gamma = \frac{\mu_3}{\sigma^3} \]

\[ \gamma = \frac{\frac{\sum_{i=1}^{n}(x_i - \bar{x})^3}{n}}{\left(\frac{\sum_{i=1}^{n}(x_i - \bar{x})^2}{n}\right)^{3/2}} \]

\(\mu_3\) - trzeci moment centralny  
\(\sigma\) - odchylenie standardowe

Kurtoza: \[ \kappa = \frac{\mu_4}{\sigma^4} \]

## Cetralne twierdzenie graniczne

\(\bar{X}_{\bar{X}} = \mu)\)

Czyli, ze średnia ze średnich w próbach jest równa średniej populacji

\(s^2_{\bar{X}} = \frac{\sigma^2}n)\)

Błąd standardowy: \(s_e = \sqrt{\frac{\sigma^2}n} = \sigma\sqrt{\frac{1}n}\)

## Testowanie średnich

statystyka testowa \(z\): \(z = \frac{\bar{X} - \mu}{s_e}\)

Przedział ufności dla średniej: \((\bar{X} - z \cdot s_e) < \mu <(\bar{X} + z \cdot s_e)\)

## Kowariancja i korelacja

Kowariancja

\(cov_{jk} = \frac{SP_{jk}}{n -1}\)  

gdzie  

\(SP_{jk} = \sum_{i=1}^{n}(x_{ij}-\bar{X_j})(x_{ik}-\bar{X_k})\)

Korelacja Pearson'a: \(r_{jk} = \frac{cov_{jk}}{s_{j}s_{k}}\)   
Korelacja Spearman'a: \(r' = \frac{6\sum_{i=1}^{n}[R(x_i) - R(y_i)]^2}{n(n^2-1)}\)  
Gdzie \(R\) wskazuje na rangę


